// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: baseledger/BaseledgerTransaction.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BaseledgerTransaction struct {
	Creator                 string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id                      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BaseledgerTransactionId string `protobuf:"bytes,3,opt,name=baseledgerTransactionId,proto3" json:"baseledgerTransactionId,omitempty"`
	Payload                 string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	OpCode                  uint32 `protobuf:"varint,5,opt,name=opCode,proto3" json:"opCode,omitempty"`
}

func (m *BaseledgerTransaction) Reset()         { *m = BaseledgerTransaction{} }
func (m *BaseledgerTransaction) String() string { return proto.CompactTextString(m) }
func (*BaseledgerTransaction) ProtoMessage()    {}
func (*BaseledgerTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33a2abe646017ecc, []int{0}
}
func (m *BaseledgerTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseledgerTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseledgerTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseledgerTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseledgerTransaction.Merge(m, src)
}
func (m *BaseledgerTransaction) XXX_Size() int {
	return m.Size()
}
func (m *BaseledgerTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseledgerTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_BaseledgerTransaction proto.InternalMessageInfo

func (m *BaseledgerTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *BaseledgerTransaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BaseledgerTransaction) GetBaseledgerTransactionId() string {
	if m != nil {
		return m.BaseledgerTransactionId
	}
	return ""
}

func (m *BaseledgerTransaction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *BaseledgerTransaction) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseledgerTransaction)(nil), "unibrightio.baseledger.baseledger.BaseledgerTransaction")
}

func init() {
	proto.RegisterFile("baseledger/BaseledgerTransaction.proto", fileDescriptor_33a2abe646017ecc)
}

var fileDescriptor_33a2abe646017ecc = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0x4a, 0x2c, 0x4e,
	0xcd, 0x49, 0x4d, 0x49, 0x4f, 0x2d, 0xd2, 0x77, 0x82, 0x33, 0x43, 0x8a, 0x12, 0xf3, 0x8a, 0x13,
	0x93, 0x4b, 0x32, 0xf3, 0xf3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x14, 0x4b, 0xf3, 0x32,
	0x93, 0x8a, 0x32, 0xd3, 0x33, 0x4a, 0x32, 0xf3, 0xf5, 0x10, 0x7a, 0x90, 0x98, 0x52, 0x22, 0xe9,
	0xf9, 0xe9, 0xf9, 0x60, 0xd5, 0xfa, 0x20, 0x16, 0x44, 0xa3, 0xd2, 0x5a, 0x46, 0x2e, 0x51, 0xac,
	0x06, 0x0b, 0x49, 0x70, 0xb1, 0x27, 0x17, 0xa5, 0x26, 0x96, 0xe4, 0x17, 0x49, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x4c, 0x60, 0x41, 0xa6,
	0xcc, 0x14, 0x21, 0x0b, 0x2e, 0xf1, 0x24, 0x6c, 0x46, 0x78, 0xa6, 0x48, 0x30, 0x83, 0x15, 0xe1,
	0x92, 0x06, 0xd9, 0x51, 0x90, 0x58, 0x99, 0x93, 0x9f, 0x98, 0x22, 0xc1, 0x02, 0xb1, 0x03, 0xca,
	0x15, 0x12, 0xe3, 0x62, 0xcb, 0x2f, 0x70, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x55, 0x60, 0xd4, 0xe0,
	0x0d, 0x82, 0xf2, 0x9c, 0xfc, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23,
	0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca,
	0x24, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0x29, 0x34, 0xf4, 0x91,
	0x42, 0xb0, 0x02, 0x99, 0x53, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x0e, 0x06, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x1a, 0xb4, 0xcb, 0x69, 0x01, 0x00, 0x00,
}

func (m *BaseledgerTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseledgerTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseledgerTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OpCode != 0 {
		i = encodeVarintBaseledgerTransaction(dAtA, i, uint64(m.OpCode))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintBaseledgerTransaction(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BaseledgerTransactionId) > 0 {
		i -= len(m.BaseledgerTransactionId)
		copy(dAtA[i:], m.BaseledgerTransactionId)
		i = encodeVarintBaseledgerTransaction(dAtA, i, uint64(len(m.BaseledgerTransactionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintBaseledgerTransaction(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBaseledgerTransaction(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBaseledgerTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovBaseledgerTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BaseledgerTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBaseledgerTransaction(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovBaseledgerTransaction(uint64(l))
	}
	l = len(m.BaseledgerTransactionId)
	if l > 0 {
		n += 1 + l + sovBaseledgerTransaction(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovBaseledgerTransaction(uint64(l))
	}
	if m.OpCode != 0 {
		n += 1 + sovBaseledgerTransaction(uint64(m.OpCode))
	}
	return n
}

func sovBaseledgerTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBaseledgerTransaction(x uint64) (n int) {
	return sovBaseledgerTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BaseledgerTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBaseledgerTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseledgerTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseledgerTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseledgerTransactionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseledgerTransactionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpCode", wireType)
			}
			m.OpCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpCode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBaseledgerTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBaseledgerTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBaseledgerTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBaseledgerTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBaseledgerTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBaseledgerTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBaseledgerTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBaseledgerTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBaseledgerTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBaseledgerTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBaseledgerTransaction = fmt.Errorf("proto: unexpected end of group")
)
