// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: baseledger/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreateBaseledgerTransaction struct {
	Creator                 string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id                      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BaseledgerTransactionId string `protobuf:"bytes,3,opt,name=baseledgerTransactionId,proto3" json:"baseledgerTransactionId,omitempty"`
	Payload                 string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	OpCode                  uint32 `protobuf:"varint,5,opt,name=opCode,proto3" json:"opCode,omitempty"`
}

func (m *MsgCreateBaseledgerTransaction) Reset()         { *m = MsgCreateBaseledgerTransaction{} }
func (m *MsgCreateBaseledgerTransaction) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBaseledgerTransaction) ProtoMessage()    {}
func (*MsgCreateBaseledgerTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a950a50e793e692a, []int{0}
}
func (m *MsgCreateBaseledgerTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBaseledgerTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBaseledgerTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBaseledgerTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBaseledgerTransaction.Merge(m, src)
}
func (m *MsgCreateBaseledgerTransaction) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBaseledgerTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBaseledgerTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBaseledgerTransaction proto.InternalMessageInfo

func (m *MsgCreateBaseledgerTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateBaseledgerTransaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgCreateBaseledgerTransaction) GetBaseledgerTransactionId() string {
	if m != nil {
		return m.BaseledgerTransactionId
	}
	return ""
}

func (m *MsgCreateBaseledgerTransaction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *MsgCreateBaseledgerTransaction) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

type MsgCreateBaseledgerTransactionResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateBaseledgerTransactionResponse) Reset() {
	*m = MsgCreateBaseledgerTransactionResponse{}
}
func (m *MsgCreateBaseledgerTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBaseledgerTransactionResponse) ProtoMessage()    {}
func (*MsgCreateBaseledgerTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a950a50e793e692a, []int{1}
}
func (m *MsgCreateBaseledgerTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBaseledgerTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBaseledgerTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBaseledgerTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBaseledgerTransactionResponse.Merge(m, src)
}
func (m *MsgCreateBaseledgerTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBaseledgerTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBaseledgerTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBaseledgerTransactionResponse proto.InternalMessageInfo

func (m *MsgCreateBaseledgerTransactionResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgUpdateBaseledgerTransaction struct {
	Creator                 string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id                      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BaseledgerTransactionId string `protobuf:"bytes,3,opt,name=baseledgerTransactionId,proto3" json:"baseledgerTransactionId,omitempty"`
	Payload                 string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	OpCode                  uint32 `protobuf:"varint,5,opt,name=opCode,proto3" json:"opCode,omitempty"`
}

func (m *MsgUpdateBaseledgerTransaction) Reset()         { *m = MsgUpdateBaseledgerTransaction{} }
func (m *MsgUpdateBaseledgerTransaction) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBaseledgerTransaction) ProtoMessage()    {}
func (*MsgUpdateBaseledgerTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a950a50e793e692a, []int{2}
}
func (m *MsgUpdateBaseledgerTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBaseledgerTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBaseledgerTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBaseledgerTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBaseledgerTransaction.Merge(m, src)
}
func (m *MsgUpdateBaseledgerTransaction) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBaseledgerTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBaseledgerTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBaseledgerTransaction proto.InternalMessageInfo

func (m *MsgUpdateBaseledgerTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateBaseledgerTransaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgUpdateBaseledgerTransaction) GetBaseledgerTransactionId() string {
	if m != nil {
		return m.BaseledgerTransactionId
	}
	return ""
}

func (m *MsgUpdateBaseledgerTransaction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *MsgUpdateBaseledgerTransaction) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

type MsgUpdateBaseledgerTransactionResponse struct {
}

func (m *MsgUpdateBaseledgerTransactionResponse) Reset() {
	*m = MsgUpdateBaseledgerTransactionResponse{}
}
func (m *MsgUpdateBaseledgerTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBaseledgerTransactionResponse) ProtoMessage()    {}
func (*MsgUpdateBaseledgerTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a950a50e793e692a, []int{3}
}
func (m *MsgUpdateBaseledgerTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBaseledgerTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBaseledgerTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBaseledgerTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBaseledgerTransactionResponse.Merge(m, src)
}
func (m *MsgUpdateBaseledgerTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBaseledgerTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBaseledgerTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBaseledgerTransactionResponse proto.InternalMessageInfo

type MsgDeleteBaseledgerTransaction struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteBaseledgerTransaction) Reset()         { *m = MsgDeleteBaseledgerTransaction{} }
func (m *MsgDeleteBaseledgerTransaction) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBaseledgerTransaction) ProtoMessage()    {}
func (*MsgDeleteBaseledgerTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a950a50e793e692a, []int{4}
}
func (m *MsgDeleteBaseledgerTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBaseledgerTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBaseledgerTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBaseledgerTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBaseledgerTransaction.Merge(m, src)
}
func (m *MsgDeleteBaseledgerTransaction) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBaseledgerTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBaseledgerTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBaseledgerTransaction proto.InternalMessageInfo

func (m *MsgDeleteBaseledgerTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteBaseledgerTransaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgDeleteBaseledgerTransactionResponse struct {
}

func (m *MsgDeleteBaseledgerTransactionResponse) Reset() {
	*m = MsgDeleteBaseledgerTransactionResponse{}
}
func (m *MsgDeleteBaseledgerTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBaseledgerTransactionResponse) ProtoMessage()    {}
func (*MsgDeleteBaseledgerTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a950a50e793e692a, []int{5}
}
func (m *MsgDeleteBaseledgerTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBaseledgerTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBaseledgerTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBaseledgerTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBaseledgerTransactionResponse.Merge(m, src)
}
func (m *MsgDeleteBaseledgerTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBaseledgerTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBaseledgerTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBaseledgerTransactionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateBaseledgerTransaction)(nil), "unibrightio.baseledger.baseledger.MsgCreateBaseledgerTransaction")
	proto.RegisterType((*MsgCreateBaseledgerTransactionResponse)(nil), "unibrightio.baseledger.baseledger.MsgCreateBaseledgerTransactionResponse")
	proto.RegisterType((*MsgUpdateBaseledgerTransaction)(nil), "unibrightio.baseledger.baseledger.MsgUpdateBaseledgerTransaction")
	proto.RegisterType((*MsgUpdateBaseledgerTransactionResponse)(nil), "unibrightio.baseledger.baseledger.MsgUpdateBaseledgerTransactionResponse")
	proto.RegisterType((*MsgDeleteBaseledgerTransaction)(nil), "unibrightio.baseledger.baseledger.MsgDeleteBaseledgerTransaction")
	proto.RegisterType((*MsgDeleteBaseledgerTransactionResponse)(nil), "unibrightio.baseledger.baseledger.MsgDeleteBaseledgerTransactionResponse")
}

func init() { proto.RegisterFile("baseledger/tx.proto", fileDescriptor_a950a50e793e692a) }

var fileDescriptor_a950a50e793e692a = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4a, 0x2c, 0x4e,
	0xcd, 0x49, 0x4d, 0x49, 0x4f, 0x2d, 0xd2, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x52, 0x2c, 0xcd, 0xcb, 0x4c, 0x2a, 0xca, 0x4c, 0xcf, 0x28, 0xc9, 0xcc, 0xd7, 0x43, 0x28, 0x40,
	0x62, 0x4a, 0xa9, 0x21, 0xe9, 0x73, 0x82, 0x33, 0x43, 0x8a, 0x12, 0xf3, 0x8a, 0x13, 0x93, 0x4b,
	0x32, 0xf3, 0xf3, 0x20, 0x46, 0x29, 0x6d, 0x63, 0xe4, 0x92, 0xf3, 0x2d, 0x4e, 0x77, 0x2e, 0x4a,
	0x4d, 0x2c, 0x49, 0xc5, 0xaa, 0x50, 0x48, 0x82, 0x8b, 0x3d, 0x19, 0x24, 0x9d, 0x5f, 0x24, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x81,
	0x05, 0x99, 0x32, 0x53, 0x84, 0x2c, 0xb8, 0xc4, 0x93, 0xb0, 0x19, 0xe1, 0x99, 0x22, 0xc1, 0x0c,
	0x56, 0x84, 0x4b, 0x1a, 0x64, 0x47, 0x41, 0x62, 0x65, 0x4e, 0x7e, 0x62, 0x8a, 0x04, 0x0b, 0xc4,
	0x0e, 0x28, 0x57, 0x48, 0x8c, 0x8b, 0x2d, 0xbf, 0xc0, 0x39, 0x3f, 0x25, 0x55, 0x82, 0x55, 0x81,
	0x51, 0x83, 0x37, 0x08, 0xca, 0x53, 0xb2, 0xe0, 0x52, 0xc3, 0xef, 0xee, 0xa0, 0xd4, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0xa8, 0x2b, 0x19, 0x61, 0xae, 0x84, 0x79, 0x39, 0xb4, 0x20, 0x65, 0x88,
	0x79, 0x59, 0x03, 0xec, 0x65, 0x3c, 0xee, 0x86, 0x79, 0x59, 0xc9, 0x0b, 0xec, 0x43, 0x97, 0xd4,
	0x9c, 0x54, 0x8a, 0x7d, 0x08, 0xb5, 0x15, 0x8f, 0x59, 0x30, 0x5b, 0x8d, 0xfa, 0x59, 0xb8, 0x98,
	0x7d, 0x8b, 0xd3, 0x85, 0x56, 0x33, 0x72, 0x49, 0xe3, 0x4b, 0x50, 0x8e, 0x7a, 0x04, 0xd3, 0xaf,
	0x1e, 0xfe, 0xb8, 0x95, 0xf2, 0xa4, 0xd8, 0x08, 0x78, 0xf2, 0x00, 0xb9, 0x16, 0x5f, 0x5a, 0x20,
	0xd2, 0xb5, 0x78, 0x8c, 0x20, 0xd6, 0xb5, 0x44, 0xc4, 0x2c, 0xd8, 0xb5, 0xf8, 0xe2, 0x95, 0x48,
	0xd7, 0xe2, 0x31, 0x82, 0x58, 0xd7, 0x12, 0x91, 0x22, 0x9c, 0xfc, 0x4e, 0x3c, 0x92, 0x63, 0xbc,
	0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63,
	0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x24, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f,
	0x57, 0x1f, 0xc9, 0x3a, 0x7d, 0xa4, 0x62, 0xab, 0x02, 0x99, 0x53, 0x52, 0x59, 0x90, 0x5a, 0x9c,
	0xc4, 0x06, 0x2e, 0xb4, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x0e, 0x67, 0x57, 0x16,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateBaseledgerTransaction(ctx context.Context, in *MsgCreateBaseledgerTransaction, opts ...grpc.CallOption) (*MsgCreateBaseledgerTransactionResponse, error)
	UpdateBaseledgerTransaction(ctx context.Context, in *MsgUpdateBaseledgerTransaction, opts ...grpc.CallOption) (*MsgUpdateBaseledgerTransactionResponse, error)
	DeleteBaseledgerTransaction(ctx context.Context, in *MsgDeleteBaseledgerTransaction, opts ...grpc.CallOption) (*MsgDeleteBaseledgerTransactionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateBaseledgerTransaction(ctx context.Context, in *MsgCreateBaseledgerTransaction, opts ...grpc.CallOption) (*MsgCreateBaseledgerTransactionResponse, error) {
	out := new(MsgCreateBaseledgerTransactionResponse)
	err := c.cc.Invoke(ctx, "/unibrightio.baseledger.baseledger.Msg/CreateBaseledgerTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBaseledgerTransaction(ctx context.Context, in *MsgUpdateBaseledgerTransaction, opts ...grpc.CallOption) (*MsgUpdateBaseledgerTransactionResponse, error) {
	out := new(MsgUpdateBaseledgerTransactionResponse)
	err := c.cc.Invoke(ctx, "/unibrightio.baseledger.baseledger.Msg/UpdateBaseledgerTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteBaseledgerTransaction(ctx context.Context, in *MsgDeleteBaseledgerTransaction, opts ...grpc.CallOption) (*MsgDeleteBaseledgerTransactionResponse, error) {
	out := new(MsgDeleteBaseledgerTransactionResponse)
	err := c.cc.Invoke(ctx, "/unibrightio.baseledger.baseledger.Msg/DeleteBaseledgerTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateBaseledgerTransaction(context.Context, *MsgCreateBaseledgerTransaction) (*MsgCreateBaseledgerTransactionResponse, error)
	UpdateBaseledgerTransaction(context.Context, *MsgUpdateBaseledgerTransaction) (*MsgUpdateBaseledgerTransactionResponse, error)
	DeleteBaseledgerTransaction(context.Context, *MsgDeleteBaseledgerTransaction) (*MsgDeleteBaseledgerTransactionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateBaseledgerTransaction(ctx context.Context, req *MsgCreateBaseledgerTransaction) (*MsgCreateBaseledgerTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBaseledgerTransaction not implemented")
}
func (*UnimplementedMsgServer) UpdateBaseledgerTransaction(ctx context.Context, req *MsgUpdateBaseledgerTransaction) (*MsgUpdateBaseledgerTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBaseledgerTransaction not implemented")
}
func (*UnimplementedMsgServer) DeleteBaseledgerTransaction(ctx context.Context, req *MsgDeleteBaseledgerTransaction) (*MsgDeleteBaseledgerTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBaseledgerTransaction not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateBaseledgerTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateBaseledgerTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBaseledgerTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unibrightio.baseledger.baseledger.Msg/CreateBaseledgerTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBaseledgerTransaction(ctx, req.(*MsgCreateBaseledgerTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBaseledgerTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBaseledgerTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBaseledgerTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unibrightio.baseledger.baseledger.Msg/UpdateBaseledgerTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBaseledgerTransaction(ctx, req.(*MsgUpdateBaseledgerTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteBaseledgerTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteBaseledgerTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteBaseledgerTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unibrightio.baseledger.baseledger.Msg/DeleteBaseledgerTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteBaseledgerTransaction(ctx, req.(*MsgDeleteBaseledgerTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unibrightio.baseledger.baseledger.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBaseledgerTransaction",
			Handler:    _Msg_CreateBaseledgerTransaction_Handler,
		},
		{
			MethodName: "UpdateBaseledgerTransaction",
			Handler:    _Msg_UpdateBaseledgerTransaction_Handler,
		},
		{
			MethodName: "DeleteBaseledgerTransaction",
			Handler:    _Msg_DeleteBaseledgerTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baseledger/tx.proto",
}

func (m *MsgCreateBaseledgerTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBaseledgerTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBaseledgerTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OpCode != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OpCode))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BaseledgerTransactionId) > 0 {
		i -= len(m.BaseledgerTransactionId)
		copy(dAtA[i:], m.BaseledgerTransactionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BaseledgerTransactionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateBaseledgerTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBaseledgerTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBaseledgerTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBaseledgerTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBaseledgerTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBaseledgerTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OpCode != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OpCode))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BaseledgerTransactionId) > 0 {
		i -= len(m.BaseledgerTransactionId)
		copy(dAtA[i:], m.BaseledgerTransactionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BaseledgerTransactionId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBaseledgerTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBaseledgerTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBaseledgerTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBaseledgerTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBaseledgerTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBaseledgerTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBaseledgerTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBaseledgerTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBaseledgerTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateBaseledgerTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BaseledgerTransactionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OpCode != 0 {
		n += 1 + sovTx(uint64(m.OpCode))
	}
	return n
}

func (m *MsgCreateBaseledgerTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateBaseledgerTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BaseledgerTransactionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OpCode != 0 {
		n += 1 + sovTx(uint64(m.OpCode))
	}
	return n
}

func (m *MsgUpdateBaseledgerTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteBaseledgerTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteBaseledgerTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateBaseledgerTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBaseledgerTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBaseledgerTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseledgerTransactionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseledgerTransactionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpCode", wireType)
			}
			m.OpCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpCode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBaseledgerTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBaseledgerTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBaseledgerTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBaseledgerTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBaseledgerTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBaseledgerTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseledgerTransactionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseledgerTransactionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpCode", wireType)
			}
			m.OpCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpCode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBaseledgerTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBaseledgerTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBaseledgerTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBaseledgerTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBaseledgerTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBaseledgerTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBaseledgerTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBaseledgerTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBaseledgerTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
