version: '3.8'

services:
  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=ub
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<pass>
    volumes:
      - baseledger-db:/var/lib/postgresql/data
    networks:
      - baseledger
    hostname: postgres-local-node
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    restart: always
  nats:
    image: nats
    command: ["--auth", <nats_token>, "-DV"]
    hostname:
      nats-local-node
    networks:
      - baseledger
    ports:
      - ${NATS_EXPOSED_PORT}:4222
    restart: always
  blockchain_app:
      image: baseledger/blockchain_app
      networks:
        - baseledger
      ports:
        - ${BLOCKCHAIN_APP_API_PORT}:1317
        - ${TENDERMINT_NODE_PORT}:26656
        - ${TENDERMINT_NODE_GRPC_PORT}:26657
      extra_hosts:
          - "host.docker.internal:host-gateway" # enable targeting host machine with host.docker.internal
  proxy_app:
    image: baseledger/proxy_app
    environment:
      - DB_HOST=postgres-local-node
      - ORGANIZATION_ID=${ORGANIZATION_ID}
      - API_CONCIRCLE_URL=${API_CONCIRCLE_URL}
    networks:
      - baseledger
    ports:
      - ${PROXY_APP_PORT}:8080
    extra_hosts:
        - "host.docker.internal:host-gateway" # enable targeting host machine with host.docker.internal
    depends_on:
        - postgres
        - nats

networks:
  baseledger:
    driver: bridge

volumes:
  baseledger-db:    